export const LOADING='LOADING'
// get all products

export const GET_ALL_PRODUCTS_SUCCESS='GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAILED='GET_ALL_PRODUCTS_FAILED'

//add prod
export const ADD_PRODUCT_SUCCESS='ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILED='ADD_PRODUCT_FAILED'